# Generated by Django 2.0.5 on 2018-11-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0006_suitproductmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productType',
            field=models.IntegerField(default=2),
        ),
    ]
