# Generated by Django 2.0.5 on 2018-09-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('testcase', '0005_merge_20180920_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuitCaseMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.IntegerField()),
                ('case', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.IntegerField()),
                ('desc', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.IntegerField()),
                ('desc', models.CharField(max_length=100, null=True)),
                ('setup', models.IntegerField(null=True)),
                ('teardown', models.IntegerField(null=True)),
            ],
        ),
    ]
