# Generated by Django 2.0.5 on 2018-09-30 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('testcase', '0006_suitcasemapping_testsuite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suitcasemapping',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='suitcasemapping',
            name='create_user',
        ),
    ]
