# Generated by Django 2.1.2 on 2018-10-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0007_auto_20181006_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suitcasemapping',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='suitcasemapping',
            name='create_user',
        ),
    ]
