# Generated by Django 2.0.5 on 2018-11-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('testcase', '0008_auto_20181011_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiteScriptMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite', models.IntegerField()),
                ('script', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='casemodule',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='casemodule',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='casemodule',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='last_run_time',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='run_count',
        ),
        migrations.AddField(
            model_name='casemodule',
            name='child_module',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='casemodule',
            name='parent_module',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='casemodule',
            name='product',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
