# Generated by Django 2.0.5 on 2018-10-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('desc', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('test_times', models.IntegerField()),
                ('status', models.IntegerField()),
                ('product', models.IntegerField()),
                ('suit', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.IntegerField()),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
    ]
