# Generated by Django 2.0.5 on 2018-10-18 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0002_testtask_run_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtask',
            name='test_times',
        ),
    ]
