# Generated by Django 2.0.5 on 2018-10-21 04:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0003_remove_testtask_test_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtask',
            name='run_time',
        ),
    ]
