# Generated by Django 2.0.5 on 2018-11-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0004_remove_testtask_run_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedTask',
            fields=[
                ('task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('async_result_id', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=100)),
                ('log_title', models.CharField(max_length=100)),
                ('task', models.IntegerField()),
                ('result', models.IntegerField(default=0)),
                ('run_time', models.DateTimeField()),
                ('run_user', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaskSuiteMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.IntegerField()),
                ('suite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestResultType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='testtask',
            name='suit',
        ),
        migrations.AddField(
            model_name='testtask',
            name='last_run_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='testtask',
            name='runtime',
            field=models.IntegerField(default=0),
        ),
    ]
