# Generated by Django 2.0.5 on 2018-11-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_auto_20180910_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='无', max_length=20),
        ),
    ]
