# Generated by Django 2.0.5 on 2018-09-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('script', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='script',
            name='last_edit_user',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='last_run_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='run_count',
            field=models.IntegerField(default=0),
        ),
    ]
