# Generated by Django 2.0.5 on 2018-09-29 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('script', '0003_suitcasemapping_testsuite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuitCaseMapping',
        ),
        migrations.DeleteModel(
            name='TestSuite',
        ),
    ]
